[[_overview]]

== 授权服务概述

:tech_feature_name: 授权服务

{project_name}支持细粒度的授权策略，能够结合不同的访问控制机制，例如

* 基于属性的访问控制 (ABAC)
* 基于角色的访问控制（RBAC）
* 基于用户的访问控制 (UBAC)
* 基于上下文的访问控制 (CBAC)
* 基于规则的访问控制
    ** 使用 JavaScript
* 基于时间的访问控制
* 通过服务提供商接口（SPI）支持自定义访问控制机制（ACM）

{project_name}基于一套管理用户界面和 RESTful API，提供了必要的手段来为受保护的资源和范围创建权限，将这些权限与授权策略关联，并在应用程序和服务中执行授权决策。

资源服务器（为受保护资源提供服务的应用程序或服务）通常依赖某种信息来决定是否允许访问受保护资源。对于基于 RESTful 的资源服务器来说，这些信息通常是从安全令牌中获取的，安全令牌通常作为承载令牌在每次请求服务器时发送。对于依赖会话验证用户身份的网络应用程序，该信息通常存储在用户的会话中，并在每次请求时从中获取。

资源服务器通常只根据基于角色的访问控制（RBAC）来执行授权决策，即根据映射到这些相同资源的角色来检查授予试图访问受保护资源的用户的角色。虽然角色非常有用，应用程序也会使用，但它们也有一些局限性：

* 资源和角色是紧密耦合的，对角色的更改（如添加、删除或更改访问上下文）会影响多个资源
* 安全要求的改变可能意味着要对应用程序代码进行深度修改，以反映这些改变
* 根据应用程序的规模，角色管理可能会变得困难且容易出错
* 它不是最灵活的访问控制机制。角色并不代表你是谁，而且缺乏上下文信息。如果你被授予一个角色，那么你至少有一些访问权限。

考虑到如今我们需要考虑异构环境，用户分布在不同地区，使用不同的本地策略、
在这种环境中，用户分布在不同地区，使用不同的本地策略，使用不同的设备，而且对信息共享的需求很高，{project_name}授权服务可通过以下方式帮助您提高应用程序和服务的授权能力：

* 使用细粒度授权策略和不同的访问控制机制保护资源
* 集中式资源、权限和策略管理
* 集中式政策决策点
* 基于一套 REST 授权服务的 REST 安全性
* 授权工作流和用户管理访问
* 帮助避免跨项目（和重新部署）代码复制并快速适应安全需求变化的基础架构。