<#import "/templates/guide.adoc" as tmpl>
<#import "/templates/kc.adoc" as kc>
<#import "/templates/links.adoc" as links>
<#import "/templates/profile.adoc" as profile>

<@tmpl.guide
title="Configuring logging"
summary="Learn how to configure Logging"
includedOptions="log log-*">

{project_name} uses the JBoss Logging framework. The following is a high-level overview for the available log handlers:

* root
** console (_default_)
** file
** Syslog
<@profile.ifCommunity>
** GELF
</@profile.ifCommunity>

== Logging configuration
Logging is done on a per-category basis in {project_name}. You can configure logging for the root log level or for more specific categories such as `org.hibernate` or `org.keycloak`. This {section} describes how to configure logging.

=== Log levels

The following table defines the available log levels.

[%autowidth]
|===
|Level|Description

|FATAL|Critical failures with complete inability to serve any kind of request.
|ERROR|A significant error or problem leading to the inability to process requests.
|WARN|A non-critical error or problem that might not require immediate correction.
|INFO|{project_name} lifecycle events or important information. Low frequency.
|DEBUG|More detailed information for debugging purposes, such as database logs. Higher frequency.
|TRACE|Most detailed debugging information. Very high frequency.
|ALL|Special level for all log messages.
|OFF|Special level to turn logging off entirely (not recommended).
|===

=== Configuring the root log level
When no log level configuration exists for a more specific category logger, the enclosing category is used instead. When there is no enclosing category, the root logger level is used.

To set the root log level, enter the following command:

<@kc.start parameters="--log-level=<root-level>"/>

Use these guidelines for this command:

* For `_<root-level>_`, supply a level defined in the preceding table.
* The log level is case-insensitive. For example, you could either use `DEBUG` or `debug`.
* If you were to accidentally set the log level twice, the last occurrence in the list becomes the log level. For example, if you included the syntax `--log-level="info,...,DEBUG,..."`, the root logger would be `DEBUG`.

=== Configuring category-specific log levels
You can set different log levels for specific areas in {project_name}. Use this command to provide a comma-separated list of categories for which you want a different log level:

<@kc.start parameters="--log-level=\"<root-level>,<org.category1>:<org.category1-level>\""/>

A configuration that applies to a category also applies to its sub-categories unless you include a more specific matching sub-category.

.Example
<@kc.start parameters="--log-level=\"INFO,org.hibernate:debug,org.hibernate.hql.internal.ast:info\""/>

This example sets the following log levels:

* Root log level for all loggers is set to INFO.
* The hibernate log level in general is set to debug.
* To keep SQL abstract syntax trees from creating verbose log output, the specific subcategory `org.hibernate.hql.internal.ast` is set to info. As a result, the SQL abstract syntax trees are omitted instead of appearing at the `debug` level.

== Enabling log handlers
To enable log handlers, enter the following command:

<@kc.start parameters="--log=\"<handler1>,<handler2>\""/>

The available handlers are
<@profile.ifCommunity>
`console`, `file`, `syslog` and `gelf`.
</@profile.ifCommunity>
<@profile.ifProduct>
`console`, `file` and `syslog`.
</@profile.ifProduct>
The more specific handler configuration mentioned below will only take effect when the handler is added to this comma-separated list.

== Console log handler
The console log handler is enabled by default, providing unstructured log messages for the console.

=== Configuring the console log format
{project_name} uses a pattern-based logging formatter that generates human-readable text logs by default.

The logging format template for these lines can be applied at the root level. The default format template is:

* `%d{yyyy-MM-dd HH:mm:ss,SSS} %-5p [%c] (%t) %s%e%n`

The format string supports the symbols in the following table:

[%autowidth]
|===
|Symbol|Summary|Description

|%%|%|Renders a simple % character.
|%c|Category|Renders the log category name.
|++%d{xxx}++|Date|Renders a date with the given date format string.String syntax defined by `java.text.SimpleDateFormat`
|%e|Exception|Renders a thrown exception.
|%h|Hostname|Renders the simple host name.
|%H|Qualified host name|Renders the fully qualified hostname, which may be the same as the simple host name, depending on the OS configuration.
|%i|Process ID|Renders the current process PID.
|%m|Full Message|Renders the log message and an exception, if thrown.
|%n |Newline|Renders the platform-specific line separator string.
|%N|Process name|Renders the name of the current process.
|%p|Level|Renders the log level of the message.
|%r|Relative time|Render the time in milliseconds since the start of the application log.
|%s|Simple message|Renders only the log message without exception trace.
|%t|Thread name|Renders the thread name.
|%t++{id}++|Thread ID|Render the thread ID.
|%z{<zone name>}|Timezone|Set the time zone of log output to <zone name>.
|%L|Line number|Render the line number of the log message.
|===

=== Setting the logging format
To set the logging format for a logged line, perform these steps:

. Build your desired format template using the preceding table.
. Enter the following command:
+
<@kc.start parameters="--log-console-format=\"\'<format>\'\""/>

Note that you need to escape characters when invoking commands containing special shell characters such as `;` using the CLI. Therefore, consider setting it in the configuration file instead.

.Example: Abbreviate the fully qualified category name
<@kc.start parameters="--log-console-format=\"\'%d{yyyy-MM-dd HH:mm:ss,SSS} %-5p [%c{3.}] (%t) %s%e%n\'\""/>

This example abbreviates the category name to three characters by setting `[%c{3.}]` in the template instead of the default `[%c]`.

=== Configuring JSON or plain console logging
By default, the console log handler logs plain unstructured data to the console. To use structured JSON log output instead, enter the following command:

<@kc.start parameters="--log-console-output=json"/>

.Example Log Message
[source, json]
----
{"timestamp":"2022-02-25T10:31:32.452+01:00","sequence":8442,"loggerClassName":"org.jboss.logging.Logger","loggerName":"io.quarkus","level":"INFO","message":"Keycloak 18.0.0-SNAPSHOT on JVM (powered by Quarkus 2.7.2.Final) started in 3.253s. Listening on: http://0.0.0.0:8080","threadName":"main","threadId":1,"mdc":{},"ndc":"","hostName":"host-name","processName":"QuarkusEntryPoint","processId":36946}
----

When using JSON output, colors are disabled and the format settings set by `--log-console-format` will not apply.

To use unstructured logging, enter the following command:

<@kc.start parameters="--log-console-output=default"/>

.Example Log Message
[source]
----
2022-03-02 10:36:50,603 INFO  [io.quarkus] (main) Keycloak 18.0.0-SNAPSHOT on JVM (powered by Quarkus 2.7.2.Final) started in 3.615s. Listening on: http://0.0.0.0:8080
----

=== Colors
Colored console log output for unstructured logs is disabled by default. Colors may improve readability, but they can cause problems when shipping logs to external log aggregation systems. To enable or disable color-coded console log output, enter following command:

<@kc.start parameters="--log-console-color=<false|true>"/>

== File logging
As an alternative to logging to the console, you can use unstructured logging to a file.

=== Enable file logging
Logging to a file is disabled by default. To enable it, enter the following command:

<@kc.start parameters="--log=\"console,file\""/>

A log file named `keycloak.log` is created inside the `data/log` directory of your {project_name} installation.

=== Configuring the location and name of the log file

To change where the log file is created and the file name, perform these steps:

. Create a writable directory to store the log file.
+
If the directory is not writable, {project_name} will start correctly, but it will issue an error and no log file will be created.

. Enter this command:
+
<@kc.start parameters="--log=\"console,file\" --log-file=<path-to>/<your-file.log>"/>

=== Configuring the file handler format
To configure a different logging format for the file log handler, enter the following command:

<@kc.start parameters="--log-file-format=\"<pattern>\""/>

See <<Configuring the console log format>> for more information and a table of the available pattern configuration.

== 使用 Syslog 集中记录日志

{project_name} 提供向远程 Syslog 服务器发送日志的功能。
它使用 https://datatracker.ietf.org/doc/html/rfc5424[RFC 5424] 中定义的协议。

=== 启用 Syslog 处理程序
要启用 Syslog 日志记录功能，请将其添加到已激活的日志处理程序列表中，如下所示：

<@kc.start parameters="--log=\"console,syslog\""/>

=== 配置 Syslog 端点

要配置集中日志系统的端点 (_host:port_), 请输入以下命令，并用特定值代替：

<@kc.start parameters="--log=\"console,syslog\" --log-syslog-endpoint=myhost:12345"/>

启用 Syslog 处理程序后，主机将使用 `localhost` 作为主机值。
默认端口为 `514` 。

=== 配置 Syslog 协议
Syslog 使用 TCP 作为默认通信协议。
要使用 UDP 代替 TCP, 请添加 `--log-syslog-protocol` 选项，如下所示：

<@kc.start parameters="--log=\"console,syslog\" --log-syslog-protocol=udp"/>

可用的协议有 `tpc` 、 `udp` 和 `ssl-tcp` 。

=== 配置 Syslog 日志格式
要设置记录行的日志格式，请执行以下步骤：

. 使用上表创建所需的格式模板。
. 输入以下命令：
+
<@kc.start parameters="--log-syslog-format=\"\'<format>\'\""/>

请注意，使用 CLI 调用包含特殊 shell 字符如 `;` 的命令时，需要转义字符。因此，请考虑在配置文件中进行设置。

.Example: 缩写完全合格的类别名称
<@kc.start parameters="--log-syslog-format=\"\'%d{yyyy-MM-dd HH:mm:ss,SSS} %-5p [%c{3.}] (%t) %s%e%n\'\""/>

本例通过在模板中设置 `[%c{3.}]` 而不是默认的 `[%c]` ，将类别名称缩写为三个字符。

=== 配置 Syslog 结构化输出
默认情况下, Syslog 日志处理程序会向 Syslog 服务器发送普通的非结构化数据。
要使用结构化 JSON 日志输出，请输入以下命令：

<@kc.start parameters="--log-syslog-output=json"/>

.日志信息示例
[source, bash]
----
2024-04-05T12:32:20.616+02:00 mabartos keycloak 2788276 io.quarkus - {"timestamp":"2024-04-05T12:32:20.616208533+02:00","sequence":9948,"loggerClassName":"org.jboss.logging.Logger","loggerName":"io.quarkus","level":"INFO","message":"Profile prod activated. ","threadName":"main","threadId":1,"mdc":{},"ndc":"","hostName":"host","processName":"QuarkusEntryPoint","processId":2788276}
----

使用 JSON 输出时，颜色将被禁用，而且 `--log-syslog-format` 设置的格式设置将不适用。

要使用非结构化日志记录，请输入以下命令：

<@kc.start parameters="--log-syslog-output=default"/>

.日志信息示例
[source, bash]
----
2024-04-05T12:31:38.473+02:00 mabartos keycloak 2787568 io.quarkus - 2024-04-05 12:31:38,473 INFO  [io.quarkus] (main) Profile prod activated.
----

可以看到，时间戳出现了两次，因此可以通过 `--log-syslog-format` 属性进行相应修改。

<@profile.ifCommunity>

== 使用 GELF 进行集中记录
注意：对 GELF 日志处理程序的支持已过时，将在未来的 {project_name} 版本中删除。
建议使用上述 Syslog 日志处理程序作为替代。

{project_name}可将日志发送到集中式日志管理系统，如以下系统：

* Graylog
* Elasticsearch, Logstash, Kibana (ELK) 日志栈内的 Logstash
* Fluentd，位于 Elasticsearch、Fluentd 和 Kibana（EFK）日志栈内

{project_name} 使用 https://quarkus.io/guides/centralized-log-management[Quarkus Logging GELF] 扩展来支持这些环境。

=== 启用 GELF 处理程序
要启用 GELF 日志记录，请将其添加到已激活的日志处理程序列表中。

例如:
<@kc.start parameters="--log=\"console,gelf\""/>

=== Configuring the GELF handler

To configure the Host and Port of your centralized logging system, enter the following command and substitute the values with your specific values:

.Host and port of the GELF server:
<@kc.start parameters="--log=\"console,gelf\" --log-gelf-host=myhost --log-gelf-port=12345"/>

When the GELF handler is enabled, the host is using `localhost` as host value and UDP for communication. To use TCP instead of UDP, prefix the host value with `tcp:`. The Default port is `12201`.

.Include or exclude Stacktraces
{project_name} includes the complete Stacktrace inside the `StackTrace` field. To exclude this field, enter the following command:

<@kc.start parameters="--log=\"console,gelf\" --log-gelf-include-stack-trace=false"/>

.Configure the timestamp format
You can change the format of the `timestamp` field. For example, you can include the date and time down to seconds by entering the following command:

<@kc.start parameters="--log=\"console,gelf\" --log-gelf-timestamp-format=\"\'yyyy-MM-dd HH:mm:ss\'\""/>

Alternatively, you could use the config file to avoid escaping:

[source, conf]
----
log-gelf-timestamp-format=yyyy-MM-dd HH:mm:ss
----

The default timestamp format is `yyyy-MM-dd HH:mm:ss,SSS`. You can use the https://docs.oracle.com/javase/10/docs/api/java/text/SimpleDateFormat.html[available SimpleDateFormat patterns] to define an appropriate timestamp.

.Configure the facility
The `facility` field is an indicator of the process or program that is the source of log messages. The default value is `keycloak`. To set this field to your preferred identifier, enter the following command:

<@kc.start parameters="--log=\"console,gelf\" --log-gelf-facility=MyKeycloak"/>

To use the CLI to configure {project_name} and use whitespaces for `facility`, enter the following command:

<@kc.start parameters="--log=\"console,gelf\" --log-gelf-facility=\"\'my keycloak\'\""/>

Alternatively, you could use the config file to avoid escaping:

[source, conf]
----
log-gelf-facility=my keycloak
----

.Configure the default message size
To change the default message size of 8kb (8192 bytes) of GELF log messages for {project_name}, enter the following command:

<@kc.start parameters="--log=\"console,gelf\" --log-gelf-max-message-size=16384"/>

The maximum size of one GELF log message is set in Bytes. The preceding example increases the size to 16kb. When messages exceed the maximum size, GELF submits the message in multiple chunks.

.Configure sending of message parameters
{project_name} includes message parameters of the occurred log event. These fields appear in the output as `MessageParam0`, `MessageParam1`, and so on, depending on the parameter length.
To switch off this behavior, enter the following command:

<@kc.start parameters="--log=\"console,gelf\" --log-gelf-include-message-parameters=false"/>

.Configure sending of source code location
{project_name} includes the `SourceClassName`, `SourceMethodName` and `SourceSimpleClassName` fields in the GELF log messages. These fields provide detail on the location of an exception that occurred. To stop sending these fields, enter the following command:

<@kc.start parameters="--log=\"console,gelf\" --log-gelf-include-location=false"/>

=== Example: Send logs to Graylog
The following example shows how to send {project_name} logs to the Graylog centralized logging stack. This example assumes you have a container tool such as https://www.docker.com/[docker] installed to start the `compose.yml`.

==== Starting the Graylog stack
The composed stack consists of:

* Graylog
* ElasticSearch
* MongoDB

[source, yaml]
----
version: '3.8'

services:
  elasticsearch:
    image: docker.io/elastic/elasticsearch:7.10.2
    ports:
      - "9200:9200"
    environment:
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
      discovery.type: "single-node"
    networks:
      - graylog

  mongo:
    image: mongo:4.4
    networks:
      - graylog

  graylog:
    image: graylog/graylog:4.3.3
    ports:
      - "9000:9000"
      - "12201:12201/udp"
      - "1514:1514"
    environment:
      GRAYLOG_HTTP_EXTERNAL_URI: "http://127.0.0.1:9000/"
      # CHANGE ME (must be at least 16 characters)!
      GRAYLOG_PASSWORD_SECRET: "forpasswordencryption"
      # Password: admin
      GRAYLOG_ROOT_PASSWORD_SHA2: "8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918"
    networks:
      - graylog
    depends_on:
      - elasticsearch
      - mongo

networks:
  graylog:
    driver: bridge
----

Copy and save the example locally into a `compose.yml` file and enter this command:

[source,bash]
----
docker compose up -d
----
After a few seconds, the Stack is ready to serve requests.

==== Creating a Graylog UDP Input
Once the stack is running, you need to create a UDP Input Graylog listens to. You can create it from the Graylog web UI (System → Input → Select GELF UDP) available at http://localhost:9000 or using the API:

This `curl` example creates a new GELF UDP Input using the API and the default Graylog login credentials (admin/admin).

[source, bash]
----
curl -H "Content-Type: application/json" -H "Authorization: Basic YWRtaW46YWRtaW4=" -H "X-Requested-By: curl" -X POST -v -d \
'{"title":"udp input","configuration":{"recv_buffer_size":262144,"bind_address":"0.0.0.0","port":12201,"decompress_size_limit":8388608},"type":"org.graylog2.inputs.gelf.udp.GELFUDPInput","global":true}' \
http://localhost:9000/api/system/inputs
----

If the stack is still in the bootstrap phase, you receive a response containing `* Empty reply from server`. A successful response includes `HTTP/1.1 201 Created` to indicate that the UDP input is created.

==== Configure {project_name} to send logs using GELF
{project_name} needs to be configured to send logs using GELF. The appropriate configuration can be seen in the following keycloak.conf example. The example includes the `log-gelf-host` and `log-gelf-port` values. These are optional values that are included for illustration purposes; default values exist.

.{project_name} GELF Configuration

[source, conf]
----
log=console,gelf
log-gelf-host=localhost
log-gelf-port=12201
----

==== Graylog: See the results
. Open your web browser, go to `http://localhost:9000`.
. Log in to the Graylog web UI using the administrator credentials (admin/admin).
. Go to Streams, All Messages.
. Start updating the stream by pressing the Play button in the upper right corner.
. Start {project_name} using `start` or `start-dev` and your GELF config.

After a few seconds, {project_name} messages appear in the Graylog dashboard.

=== 使用 ELK 堆栈的设置示例
下面的示例展示了如何将 {project_name} 日志发送到 ELK 集中式日志栈。它假定你安装了 https://www.docker.com/[docker] 等容器工具来启动 `compose.yml`。

==== 启用 logstash GELF 插件并创建管道
Logstash 使用的输入插件可以理解和解析 GELF 格式。要在稍后启动 ELK 堆栈时激活该插件，请创建目录 `pipelines` 和位于该目录中的文件 `gelf.conf`。然后在父目录中创建一个空的 `compose.yml`。

.文件结构:
[source]
----
/ELK
  - compose.yml
  - pipelines/
    - gelf.conf
----


在 `pipelines/gelf.conf` 中添加以下内容并保存：

[source, conf]
----
input {
  gelf {
    port => 12201
  }
}
output {
  stdout {}
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
  }
}
----

该文件激活并配置 logstash GELF 插件，并将其指向正确的 elasticsearch 实例。

==== 启动 ELK 堆栈
组成的堆栈包括

* ElasticSearch
* Logstash
* Kibana

将以下内容复制到您的 `compose.yml` 文件：

[source, yaml]
----
# Launch Elasticsearch
version: '3.8'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.8.2
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    networks:
      - elk

  logstash:
    image: docker.elastic.co/logstash/logstash-oss:6.8.2
    volumes:
      - source: ./pipelines #the source dir gelf.conf resides
        target: /usr/share/logstash/pipeline
        type: bind
    ports:
      - "12201:12201/udp"
      - "5000:5000"
      - "9600:9600"
    networks:
      - elk
    depends_on:
      - elasticsearch

  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.8.2
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch

networks:
  elk:
    driver: bridge
----
输入以下命令启动堆栈：

[source, bash]
----
docker compose up -d
----
几秒钟后，堆栈就可以为请求提供服务了。

==== 配置 {project_name} 使用 GELF 发送日志
需要配置 {project_name} 使用 GELF 发送日志。适当的配置可参见下面的 keycloak.conf 示例。此示例包括 `log-gelf-host` 和 `log-gelf-port` 值。这些值是可选的，仅用于说明；默认值是存在的。

.{project_name} Gelf 配置

[source, conf]
----
log=console,gelf
log-gelf-host=localhost
log-gelf-port=12201
----

应用此配置后，使用 `start-dev` 或 `start` 启动 {project_name}。

==== Kibana: 查看结果
打开 http://localhost:5601 进入 Kibana 面板。好的监控仪表盘的具体配置不在本{小节}的讨论范围内。要了解{project_name}发送的日志是否传递到了 Kibana, 请打开 http://localhost:5601/app/kibana#/dev_tools/console?_g=()[开发工具] 并执行默认的 `match_all` 查询。日志应出现在结果字段中。

=== 为 GELF 日志记录器配置不同的日志级别
为降低日志存储成本和冗长程度，通常希望在集中式日志管理系统中只存储一部分冗长的应用程序日志。要将 {project_name} 配置为使用不同的日志级别来接收日志，请使用以下配置：

[source, conf]
----
log=console,gelf
log-gelf-level=<desired-log-level>
...
----

.示例
要在集中日志栈中只查看警告及以上级别的日志，但仍能在应用程序控制台日志中看到 INFO 级别的日志，请使用以下配置：

[source, conf]
----
log=console,gelf
log-level=INFO
log-gelf-level=warn
...
----

查看摄入的日志，你会发现只有警告或以上级别的信息才会出现。

请记住， `--log-level` 设置的是前导日志级别，例如，当你调用以下命令时：

<@kc.start parameters="--log=\"console,gelf\" --log-level=error --log-gelf-level=info"/>

错误级别以下的信息将不会发送到日志栈。也就是说，即使是本例中的 GELF, 也只会收到错误级别的日志信息。

=== 配置附加键值
目前，{project_name} 配置不支持部分动态配置键，因为它们被用于 quarkus 属性中。例如，它们在定义 `quarkus.log.handler.gelf.additional-field.<my-name>.value` 时使用。

要添加用户自定义字段，可以通过 quarkus.properties 文件提供这些字段。请参阅 <@links.server id="configuration"/> 和 _使用原始Quarkus属性_ 部分。

</@profile.ifCommunity>

</@tmpl.guide>
